services:
  emby:
    image: emby/embyserver:latest
    container_name: emby
    restart: unless-stopped
    volumes:
      - ./.data/emby/config:/config
      - ./.data/emby/mnt/anime365:/mnt/anime365
    ports:
      - "8096:8096"
      - "8920:8920"
